# Generated by Django 4.2 on 2024-01-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
